spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:user-db}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create
