spring:
  datasource:
    username: ${DB_USER:user}
    password: ${DB_PASS:password}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:state_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create
